// AUTO-GENERATED by scripts/generate-testimonial-audio.py — do not edit by hand.
// Regenerate all: python3 scripts/generate-testimonial-audio.py
// Regenerate one: python3 scripts/generate-testimonial-audio.py kemi
export interface TestimonialWord { text: string; start: number; end: number }
export interface TestimonialAudio { slug: string; audio: string; words: TestimonialWord[] }

export const TESTIMONIAL_AUDIO: Record<string, TestimonialAudio> = {
  "amadi": {
    "slug": "amadi",
    "audio": "/audio/testimonial-amadi.mp3",
    "words": [
      {
        "text": "I",
        "start": 0.0,
        "end": 0.081
      },
      {
        "text": "can",
        "start": 0.151,
        "end": 0.29
      },
      {
        "text": "ask",
        "start": 0.348,
        "end": 0.534
      },
      {
        "text": "Chidi",
        "start": 0.592,
        "end": 0.929
      },
      {
        "text": "what",
        "start": 0.987,
        "end": 1.126
      },
      {
        "text": "someone",
        "start": 1.184,
        "end": 1.521
      },
      {
        "text": "bought,",
        "start": 1.567,
        "end": 2.067
      },
      {
        "text": "their",
        "start": 2.241,
        "end": 2.438
      },
      {
        "text": "size,",
        "start": 2.496,
        "end": 2.937
      },
      {
        "text": "what",
        "start": 3.053,
        "end": 3.239
      },
      {
        "text": "they",
        "start": 3.274,
        "end": 3.367
      },
      {
        "text": "asked",
        "start": 3.425,
        "end": 3.657
      },
      {
        "text": "about",
        "start": 3.692,
        "end": 3.936
      },
      {
        "text": "before.",
        "start": 3.994,
        "end": 4.586
      },
      {
        "text": "When",
        "start": 5.538,
        "end": 5.724
      },
      {
        "text": "I",
        "start": 5.77,
        "end": 5.793
      },
      {
        "text": "follow",
        "start": 5.909,
        "end": 6.188
      },
      {
        "text": "up,",
        "start": 6.258,
        "end": 6.606
      },
      {
        "text": "it",
        "start": 6.85,
        "end": 6.978
      },
      {
        "text": "feels",
        "start": 7.036,
        "end": 7.314
      },
      {
        "text": "personal,",
        "start": 7.396,
        "end": 8.139
      },
      {
        "text": "like",
        "start": 8.522,
        "end": 8.707
      },
      {
        "text": "I",
        "start": 8.742,
        "end": 8.766
      },
      {
        "text": "remembered",
        "start": 8.858,
        "end": 9.346
      },
      {
        "text": "everything",
        "start": 9.404,
        "end": 9.729
      },
      {
        "text": "myself.",
        "start": 9.787,
        "end": 10.542
      }
    ]
  },
  "titi": {
    "slug": "titi",
    "audio": "/audio/testimonial-titi.mp3",
    "words": [
      {
        "text": "Me,",
        "start": 0.0,
        "end": 0.453
      },
      {
        "text": "I'm",
        "start": 0.604,
        "end": 0.778
      },
      {
        "text": "not",
        "start": 0.836,
        "end": 0.975
      },
      {
        "text": "technical",
        "start": 0.998,
        "end": 1.451
      },
      {
        "text": "at",
        "start": 1.498,
        "end": 1.625
      },
      {
        "text": "all.",
        "start": 1.695,
        "end": 2.032
      },
      {
        "text": "I",
        "start": 2.357,
        "end": 2.426
      },
      {
        "text": "thought",
        "start": 2.554,
        "end": 2.844
      },
      {
        "text": "setting",
        "start": 2.914,
        "end": 3.262
      },
      {
        "text": "this",
        "start": 3.286,
        "end": 3.425
      },
      {
        "text": "up",
        "start": 3.495,
        "end": 3.587
      },
      {
        "text": "would",
        "start": 3.657,
        "end": 3.808
      },
      {
        "text": "stress",
        "start": 3.843,
        "end": 4.203
      },
      {
        "text": "me.",
        "start": 4.272,
        "end": 4.54
      },
      {
        "text": "But",
        "start": 4.923,
        "end": 5.074
      },
      {
        "text": "I",
        "start": 5.12,
        "end": 5.155
      },
      {
        "text": "launched",
        "start": 5.248,
        "end": 5.538
      },
      {
        "text": "my",
        "start": 5.596,
        "end": 5.666
      },
      {
        "text": "Telegram",
        "start": 5.712,
        "end": 6.118
      },
      {
        "text": "channel",
        "start": 6.177,
        "end": 6.478
      },
      {
        "text": "in",
        "start": 6.536,
        "end": 6.606
      },
      {
        "text": "a",
        "start": 6.664,
        "end": 6.687
      },
      {
        "text": "few",
        "start": 6.769,
        "end": 6.954
      },
      {
        "text": "clicks",
        "start": 7.012,
        "end": 7.361
      },
      {
        "text": "and",
        "start": 7.605,
        "end": 7.79
      },
      {
        "text": "Chidi",
        "start": 7.837,
        "end": 8.139
      },
      {
        "text": "started",
        "start": 8.185,
        "end": 8.533
      },
      {
        "text": "replying.",
        "start": 8.603,
        "end": 9.427
      }
    ]
  },
  "dami": {
    "slug": "dami",
    "audio": "/audio/testimonial-dami.mp3",
    "words": [
      {
        "text": "I",
        "start": 0.0,
        "end": 0.522
      },
      {
        "text": "used",
        "start": 0.615,
        "end": 0.778
      },
      {
        "text": "to",
        "start": 0.801,
        "end": 0.859
      },
      {
        "text": "wait",
        "start": 0.917,
        "end": 1.08
      },
      {
        "text": "till",
        "start": 1.115,
        "end": 1.265
      },
      {
        "text": "month",
        "start": 1.335,
        "end": 1.591
      },
      {
        "text": "end",
        "start": 1.66,
        "end": 1.834
      },
      {
        "text": "to",
        "start": 1.892,
        "end": 1.985
      },
      {
        "text": "know",
        "start": 2.043,
        "end": 2.159
      },
      {
        "text": "how",
        "start": 2.218,
        "end": 2.322
      },
      {
        "text": "the",
        "start": 2.38,
        "end": 2.461
      },
      {
        "text": "shop",
        "start": 2.519,
        "end": 2.752
      },
      {
        "text": "was",
        "start": 2.81,
        "end": 2.949
      },
      {
        "text": "doing.",
        "start": 3.019,
        "end": 3.413
      },
      {
        "text": "Now",
        "start": 3.855,
        "end": 4.04
      },
      {
        "text": "Chidi",
        "start": 4.122,
        "end": 4.412
      },
      {
        "text": "shows",
        "start": 4.47,
        "end": 4.748
      },
      {
        "text": "me",
        "start": 4.818,
        "end": 4.911
      },
      {
        "text": "as",
        "start": 4.969,
        "end": 5.085
      },
      {
        "text": "it",
        "start": 5.155,
        "end": 5.248
      },
      {
        "text": "happens,",
        "start": 5.306,
        "end": 6.06
      },
      {
        "text": "what's",
        "start": 6.118,
        "end": 6.42
      },
      {
        "text": "selling,",
        "start": 6.455,
        "end": 7.001
      },
      {
        "text": "what's",
        "start": 7.047,
        "end": 7.349
      },
      {
        "text": "low,",
        "start": 7.465,
        "end": 7.814
      },
      {
        "text": "where",
        "start": 7.872,
        "end": 8.069
      },
      {
        "text": "the",
        "start": 8.104,
        "end": 8.173
      },
      {
        "text": "money",
        "start": 8.231,
        "end": 8.498
      },
      {
        "text": "is.",
        "start": 8.58,
        "end": 9.288
      }
    ]
  },
  "kemi": {
    "slug": "kemi",
    "audio": "/audio/testimonial-kemi.mp3",
    "words": [
      {
        "text": "Chidi",
        "start": 0.0,
        "end": 0.313
      },
      {
        "text": "showed",
        "start": 0.372,
        "end": 0.604
      },
      {
        "text": "me",
        "start": 0.65,
        "end": 0.731
      },
      {
        "text": "the",
        "start": 0.766,
        "end": 0.836
      },
      {
        "text": "products",
        "start": 0.882,
        "end": 1.254
      },
      {
        "text": "people",
        "start": 1.289,
        "end": 1.544
      },
      {
        "text": "kept",
        "start": 1.602,
        "end": 1.846
      },
      {
        "text": "asking",
        "start": 1.904,
        "end": 2.229
      },
      {
        "text": "for",
        "start": 2.299,
        "end": 2.45
      },
      {
        "text": "in",
        "start": 2.508,
        "end": 2.612
      },
      {
        "text": "our",
        "start": 2.682,
        "end": 2.786
      },
      {
        "text": "Telegram",
        "start": 2.833,
        "end": 3.286
      },
      {
        "text": "chats.",
        "start": 3.344,
        "end": 3.82
      },
      {
        "text": "I",
        "start": 4.203,
        "end": 4.272
      },
      {
        "text": "added",
        "start": 4.365,
        "end": 4.644
      },
      {
        "text": "two",
        "start": 4.667,
        "end": 4.83
      },
      {
        "text": "new",
        "start": 4.923,
        "end": 5.085
      },
      {
        "text": "items",
        "start": 5.155,
        "end": 5.573
      },
      {
        "text": "from",
        "start": 5.619,
        "end": 5.77
      },
      {
        "text": "that,",
        "start": 5.84,
        "end": 6.235
      },
      {
        "text": "and",
        "start": 6.56,
        "end": 6.722
      },
      {
        "text": "honestly,",
        "start": 6.792,
        "end": 7.442
      },
      {
        "text": "they",
        "start": 7.616,
        "end": 7.767
      },
      {
        "text": "sold",
        "start": 7.825,
        "end": 8.057
      },
      {
        "text": "out",
        "start": 8.104,
        "end": 8.22
      },
      {
        "text": "in",
        "start": 8.278,
        "end": 8.348
      },
      {
        "text": "one",
        "start": 8.429,
        "end": 8.58
      },
      {
        "text": "week.",
        "start": 8.626,
        "end": 9.195
      }
    ]
  },
  "ngozi": {
    "slug": "ngozi",
    "audio": "/audio/testimonial-ngozi.mp3",
    "words": [
      {
        "text": "Talking",
        "start": 0.0,
        "end": 0.337
      },
      {
        "text": "to",
        "start": 0.395,
        "end": 0.488
      },
      {
        "text": "Chidi",
        "start": 0.557,
        "end": 0.813
      },
      {
        "text": "feels",
        "start": 0.871,
        "end": 1.068
      },
      {
        "text": "like",
        "start": 1.126,
        "end": 1.544
      },
      {
        "text": "talking",
        "start": 1.753,
        "end": 2.078
      },
      {
        "text": "to",
        "start": 2.125,
        "end": 2.194
      },
      {
        "text": "someone",
        "start": 2.264,
        "end": 2.705
      },
      {
        "text": "who",
        "start": 2.728,
        "end": 2.81
      },
      {
        "text": "knows",
        "start": 2.856,
        "end": 3.042
      },
      {
        "text": "my",
        "start": 3.088,
        "end": 3.17
      },
      {
        "text": "business",
        "start": 3.228,
        "end": 3.576
      },
      {
        "text": "inside",
        "start": 3.622,
        "end": 3.994
      },
      {
        "text": "out.",
        "start": 4.017,
        "end": 4.493
      },
      {
        "text": "I",
        "start": 4.934,
        "end": 4.992
      },
      {
        "text": "ask",
        "start": 5.108,
        "end": 5.375
      },
      {
        "text": "what",
        "start": 5.468,
        "end": 5.654
      },
      {
        "text": "to",
        "start": 5.7,
        "end": 5.77
      },
      {
        "text": "restock,",
        "start": 5.851,
        "end": 6.536
      },
      {
        "text": "what",
        "start": 6.711,
        "end": 6.908
      },
      {
        "text": "to",
        "start": 6.954,
        "end": 7.012
      },
      {
        "text": "promote,",
        "start": 7.094,
        "end": 7.605
      },
      {
        "text": "even",
        "start": 7.639,
        "end": 7.941
      },
      {
        "text": "what",
        "start": 8.382,
        "end": 8.591
      },
      {
        "text": "to",
        "start": 8.638,
        "end": 8.696
      },
      {
        "text": "try",
        "start": 8.742,
        "end": 8.963
      },
      {
        "text": "next,",
        "start": 9.044,
        "end": 9.578
      },
      {
        "text": "and",
        "start": 9.961,
        "end": 10.124
      },
      {
        "text": "it",
        "start": 10.194,
        "end": 10.252
      },
      {
        "text": "gives",
        "start": 10.298,
        "end": 10.495
      },
      {
        "text": "me",
        "start": 10.542,
        "end": 10.635
      },
      {
        "text": "ideas",
        "start": 10.681,
        "end": 11.064
      },
      {
        "text": "I",
        "start": 11.134,
        "end": 11.157
      },
      {
        "text": "can",
        "start": 11.227,
        "end": 11.389
      },
      {
        "text": "consider.",
        "start": 11.471,
        "end": 12.446
      }
    ]
  },
  "efe": {
    "slug": "efe",
    "audio": "/audio/testimonial-efe.mp3",
    "words": [
      {
        "text": "An",
        "start": 0.0,
        "end": 0.174
      },
      {
        "text": "influencer",
        "start": 0.255,
        "end": 0.952
      },
      {
        "text": "posted",
        "start": 1.033,
        "end": 1.486
      },
      {
        "text": "my",
        "start": 1.544,
        "end": 1.649
      },
      {
        "text": "shop",
        "start": 1.73,
        "end": 1.997
      },
      {
        "text": "and",
        "start": 2.171,
        "end": 2.438
      },
      {
        "text": "the",
        "start": 2.473,
        "end": 2.543
      },
      {
        "text": "messages",
        "start": 2.612,
        "end": 3.158
      },
      {
        "text": "just",
        "start": 3.239,
        "end": 3.46
      },
      {
        "text": "rushed",
        "start": 3.541,
        "end": 3.855
      },
      {
        "text": "in.",
        "start": 3.913,
        "end": 4.203
      },
      {
        "text": "I",
        "start": 4.644,
        "end": 4.69
      },
      {
        "text": "could",
        "start": 4.772,
        "end": 4.946
      },
      {
        "text": "not",
        "start": 5.016,
        "end": 5.166
      },
      {
        "text": "have",
        "start": 5.224,
        "end": 5.399
      },
      {
        "text": "answered",
        "start": 5.457,
        "end": 5.851
      },
      {
        "text": "all",
        "start": 5.886,
        "end": 6.026
      },
      {
        "text": "of",
        "start": 6.084,
        "end": 6.142
      },
      {
        "text": "them.",
        "start": 6.2,
        "end": 6.513
      },
      {
        "text": "Chidi",
        "start": 6.954,
        "end": 7.303
      },
      {
        "text": "kept",
        "start": 7.372,
        "end": 7.639
      },
      {
        "text": "up",
        "start": 7.697,
        "end": 7.814
      },
      {
        "text": "while",
        "start": 7.883,
        "end": 8.162
      },
      {
        "text": "I",
        "start": 8.208,
        "end": 8.243
      },
      {
        "text": "focused",
        "start": 8.359,
        "end": 8.789
      },
      {
        "text": "on",
        "start": 8.835,
        "end": 8.916
      },
      {
        "text": "packing",
        "start": 8.986,
        "end": 9.323
      },
      {
        "text": "orders.",
        "start": 9.416,
        "end": 10.217
      }
    ]
  },
  "zainab": {
    "slug": "zainab",
    "audio": "/audio/testimonial-zainab.mp3",
    "words": [
      {
        "text": "This",
        "start": 0.0,
        "end": 0.255
      },
      {
        "text": "shop",
        "start": 0.302,
        "end": 0.592
      },
      {
        "text": "is",
        "start": 0.685,
        "end": 0.836
      },
      {
        "text": "my",
        "start": 0.952,
        "end": 1.103
      },
      {
        "text": "side",
        "start": 1.196,
        "end": 1.498
      },
      {
        "text": "business,",
        "start": 1.556,
        "end": 2.043
      },
      {
        "text": "and",
        "start": 2.067,
        "end": 2.194
      },
      {
        "text": "I",
        "start": 2.276,
        "end": 2.31
      },
      {
        "text": "have",
        "start": 2.426,
        "end": 2.647
      },
      {
        "text": "two",
        "start": 2.705,
        "end": 2.926
      },
      {
        "text": "small",
        "start": 2.984,
        "end": 3.286
      },
      {
        "text": "children.",
        "start": 3.355,
        "end": 3.971
      },
      {
        "text": "Chidi",
        "start": 4.342,
        "end": 4.679
      },
      {
        "text": "handles",
        "start": 4.76,
        "end": 5.155
      },
      {
        "text": "so",
        "start": 5.19,
        "end": 5.341
      },
      {
        "text": "much",
        "start": 5.433,
        "end": 5.677
      },
      {
        "text": "of",
        "start": 5.759,
        "end": 5.898
      },
      {
        "text": "the",
        "start": 5.979,
        "end": 6.072
      },
      {
        "text": "customer",
        "start": 6.153,
        "end": 6.699
      },
      {
        "text": "chat",
        "start": 6.78,
        "end": 7.094
      },
      {
        "text": "now,",
        "start": 7.221,
        "end": 7.639
      },
      {
        "text": "so",
        "start": 7.953,
        "end": 8.197
      },
      {
        "text": "I",
        "start": 8.313,
        "end": 8.371
      },
      {
        "text": "can",
        "start": 8.487,
        "end": 8.673
      },
      {
        "text": "use",
        "start": 8.766,
        "end": 8.998
      },
      {
        "text": "that",
        "start": 9.033,
        "end": 9.253
      },
      {
        "text": "time",
        "start": 9.323,
        "end": 9.601
      },
      {
        "text": "for",
        "start": 9.648,
        "end": 9.834
      },
      {
        "text": "stock,",
        "start": 9.903,
        "end": 10.437
      },
      {
        "text": "deliveries,",
        "start": 10.484,
        "end": 11.343
      },
      {
        "text": "and",
        "start": 11.378,
        "end": 11.494
      },
      {
        "text": "my",
        "start": 11.552,
        "end": 11.668
      },
      {
        "text": "family.",
        "start": 11.784,
        "end": 12.632
      }
    ]
  },
  "palesa": {
    "slug": "palesa",
    "audio": "/audio/testimonial-palesa.mp3",
    "words": [
      {
        "text": "I",
        "start": 0.0,
        "end": 0.093
      },
      {
        "text": "spend",
        "start": 0.221,
        "end": 0.476
      },
      {
        "text": "money",
        "start": 0.546,
        "end": 0.766
      },
      {
        "text": "to",
        "start": 0.824,
        "end": 0.894
      },
      {
        "text": "bring",
        "start": 0.964,
        "end": 1.173
      },
      {
        "text": "people",
        "start": 1.242,
        "end": 1.556
      },
      {
        "text": "to",
        "start": 1.602,
        "end": 1.672
      },
      {
        "text": "my",
        "start": 1.741,
        "end": 1.834
      },
      {
        "text": "shop,",
        "start": 1.904,
        "end": 2.194
      },
      {
        "text": "so",
        "start": 2.229,
        "end": 2.345
      },
      {
        "text": "I",
        "start": 2.426,
        "end": 2.461
      },
      {
        "text": "hate",
        "start": 2.612,
        "end": 2.926
      },
      {
        "text": "wasting",
        "start": 2.995,
        "end": 3.413
      },
      {
        "text": "leads.",
        "start": 3.483,
        "end": 3.936
      },
      {
        "text": "Chidi",
        "start": 4.214,
        "end": 4.563
      },
      {
        "text": "welcomes",
        "start": 4.644,
        "end": 5.108
      },
      {
        "text": "them",
        "start": 5.166,
        "end": 5.317
      },
      {
        "text": "quickly,",
        "start": 5.399,
        "end": 5.956
      },
      {
        "text": "answers",
        "start": 6.13,
        "end": 6.629
      },
      {
        "text": "the",
        "start": 6.699,
        "end": 6.769
      },
      {
        "text": "first",
        "start": 6.838,
        "end": 7.094
      },
      {
        "text": "questions,",
        "start": 7.152,
        "end": 7.825
      },
      {
        "text": "and",
        "start": 7.976,
        "end": 8.127
      },
      {
        "text": "pushes",
        "start": 8.197,
        "end": 8.568
      },
      {
        "text": "more",
        "start": 8.638,
        "end": 8.835
      },
      {
        "text": "chats",
        "start": 8.882,
        "end": 9.242
      },
      {
        "text": "to",
        "start": 9.311,
        "end": 9.427
      },
      {
        "text": "orders.",
        "start": 9.52,
        "end": 10.263
      }
    ]
  },
  "nnenna": {
    "slug": "nnenna",
    "audio": "/audio/testimonial-nnenna.mp3",
    "words": [
      {
        "text": "Customers",
        "start": 0.0,
        "end": 0.476
      },
      {
        "text": "do",
        "start": 0.511,
        "end": 0.569
      },
      {
        "text": "not",
        "start": 0.627,
        "end": 0.743
      },
      {
        "text": "want",
        "start": 0.778,
        "end": 0.929
      },
      {
        "text": "plenty",
        "start": 0.964,
        "end": 1.382
      },
      {
        "text": "steps.",
        "start": 1.44,
        "end": 2.02
      },
      {
        "text": "If",
        "start": 2.345,
        "end": 2.485
      },
      {
        "text": "they",
        "start": 2.519,
        "end": 2.624
      },
      {
        "text": "ask",
        "start": 2.67,
        "end": 2.879
      },
      {
        "text": "inside",
        "start": 2.926,
        "end": 3.239
      },
      {
        "text": "Telegram,",
        "start": 3.262,
        "end": 3.947
      },
      {
        "text": "they",
        "start": 4.04,
        "end": 4.214
      },
      {
        "text": "want",
        "start": 4.272,
        "end": 4.458
      },
      {
        "text": "to",
        "start": 4.493,
        "end": 4.551
      },
      {
        "text": "buy",
        "start": 4.621,
        "end": 4.783
      },
      {
        "text": "there.",
        "start": 4.853,
        "end": 5.236
      },
      {
        "text": "Chidi",
        "start": 5.84,
        "end": 6.165
      },
      {
        "text": "helps",
        "start": 6.235,
        "end": 6.478
      },
      {
        "text": "them",
        "start": 6.502,
        "end": 6.653
      },
      {
        "text": "choose",
        "start": 6.734,
        "end": 7.117
      },
      {
        "text": "and",
        "start": 7.163,
        "end": 7.279
      },
      {
        "text": "confirm",
        "start": 7.349,
        "end": 7.918
      },
      {
        "text": "before",
        "start": 7.999,
        "end": 8.324
      },
      {
        "text": "they",
        "start": 8.359,
        "end": 8.475
      },
      {
        "text": "lose",
        "start": 8.545,
        "end": 8.789
      },
      {
        "text": "interest.",
        "start": 8.835,
        "end": 9.752
      }
    ]
  }
}
